start: _top+

_top: _default
   | _shells_line
   | tddft__analysis
   | adc__excited_states
   | tddft__excited_states

_shells_line: "There are" shells "shells and" basis_functions "basis functions" _NL
shells: INT
basis_functions: INT

%import .adc_excited_states.excited_states -> adc__excited_states
%import .excited_states.excited_states -> tddft__excited_states
%import .analysis.analysis -> tddft__analysis
%import .tokens._default
%import .tokens._NL
%import common.INT
%ignore " "
